programs:
  4points:
    4points.c:
      - "input_1.txt"
      - "input_2.txt"
      - "output_1.txt"
      - "output_2.txt"

  5points:
    5points.c:
      - "input_1.txt"
      - "input_2.txt"
      - "output_1.txt"
      - "output_2.txt"

  6points:
    6points.c:
      - "input_1.txt"
      - "input_2.txt"
      - "output_1.txt"
      - "output_2.txt"

  7points:
    7points.c:
      - "input_1.txt"
      - "input_2.txt"
      - "output_1.txt"
      - "output_2.txt"
  8points:
    8points/manager.c:
      - "input_1.txt"
      - "input_2.txt"
      - "output_1.txt"
      - "output_2.txt"
    8points/handler.c:
